// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfjivkdtvhqsycnjvatg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmaml2a2R0dmhxc3ljbmp2YXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzk2NTAsImV4cCI6MjA3MzcxNTY1MH0.DM6sysWTmuUvQui4jKx6EEM05Vfsy9kE70SuCGZIGaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});